version: '2'
services:
    gateway2-cassandra:
        container_name: gateway2-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/gateway2/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    gateway2-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: gateway2-cassandra-migration
        links:
            - gateway2-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
